- name: Copy cluster cleanup manifest
  copy:
    dest: "/home/{{ ansible_user }}/cluster-cleanup.yaml"
    content: |
      apiVersion: rbac.authorization.k8s.io/v1beta1
      kind: ClusterRole
      metadata:
        name: k8s-cleanup
      rules:
        - apiGroups: ["*"]
          resources: ["replicasets", "jobs", "pods"]
          verbs: ["get", "list", "delete", "update"]
      ---
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: k8s-cleanup
        namespace: kube-system
      ---
      apiVersion: rbac.authorization.k8s.io/v1beta1
      kind: ClusterRoleBinding
      metadata:
        name: k8s-cleanup
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: k8s-cleanup
      subjects:
      - kind: ServiceAccount
        name: k8s-cleanup
        namespace: kube-system
      ---
      apiVersion: extensions/v1beta1
      kind: DaemonSet
      metadata:
        name: docker-cleanup
        namespace: kube-system
      spec:
        updateStrategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 10%
        template:
          metadata:
            labels:
              app: k8s-cleanup
          spec:
            volumes:
              - name: dockersocket
                hostPath:
                  path: /var/run/docker.sock
            containers:
            - name: docker-cleanup
              image: onfido/k8s-cleanup
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 100m
                  memory: 50Mi
              volumeMounts:
                - name: dockersocket
                  mountPath: /var/run/docker.sock
      ---
      apiVersion: batch/v1beta1
      kind: CronJob
      metadata:
        name: k8s-cleanup
        namespace: kube-system
      spec:
        schedule: "0 0 * * *"
        concurrencyPolicy: "Forbid"
        jobTemplate:
          spec:
            template:
              metadata:
                name: k8s-cleanup
              spec:
                tolerations:
                - effect: NoSchedule
                  key: node-role.kubernetes.io/master
                restartPolicy: OnFailure
                serviceAccountName: k8s-cleanup
                containers:
                  - name: k8s-cleanup
                    image: onfido/k8s-cleanup
                    command: ["/bin/bash", "/bin/k8s-clean.sh"]
                    imagePullPolicy: Always
                    resources:
                      requests:
                        cpu: 100m
                        memory: 50Mi

- name: Create cleanup objects
  shell: "kubectl --context {{ item }} apply -f /home/{{ ansible_user }}/cluster-cleanup.yaml"
  with_items:
    - "{{ cluster_name }}-{{ regions.split(',')[0] }}"
    - "{{ cluster_name }}-{{ regions.split(',')[1] }}"

- name: Clean up working files
  file:
    path: "cluster-cleanup.yaml"
    state: absent
