- name: Copy flux helm operator deployment
  copy:
    dest: "/home/{{ ansible_user }}/flux-helm-operator-deployment.yaml"
    content: |
      apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      metadata:
        name: helmreleases.flux.weave.works
      spec:
        group: flux.weave.works
        names:
          kind: HelmRelease
          listKind: HelmReleaseList
          plural: helmreleases
          shortNames:
          - hr
        scope: Namespaced
        version: v1beta1
        versions:
          - name: v1beta1
            served: true
            storage: true
        validation:
          openAPIV3Schema:
            properties:
              spec:
                required: ['values', 'chart']
                properties:
                  releaseName:
                    type: string
                    pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
                  valueFileSecrets:
                    type: array
                    items:
                      type: object
                      required: ['name']
                      properties:
                        name:
                          type: string
                  values:
                    type: object
                  chart:
                    oneOf:
                    - required: ['git', 'path']
                      properties:
                        git:
                          type: string
                          format: git # not defined by OAS
                        path:
                          type: string
                        ref:
                          type: string
                    - required: ['repository', 'name', 'version']
                      properties:
                        repository:
                          type: string
                          format: url # not defined by OAS
                        name:
                          type: string
                        version:
                          type: string
                          format: semver # not defined by OAS
                        chartPullSecret:
                          properties:
                            name:
                              type: string
      ---
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: flux-helm-operator
        namespace: flux
      spec:
        replicas: 1
        selector:
          matchLabels:
            name: flux-helm-operator
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              name: flux-helm-operator
          spec:
            serviceAccount: flux
            volumes:
            - name: git-key
              secret:
                secretName: flux-git-deploy
                defaultMode: 0400 # when mounted read-only, we won't be able to chmod
            containers:
            - name: flux-helm-operator
              image: weaveworks/helm-operator:0.9.1
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
              volumeMounts:
              - name: git-key
                mountPath: /etc/fluxd/ssh

- name: Create flux helm operator deployment
  shell: "kubectl --context {{ item }} apply -f flux-helm-operator-deployment.yaml"
  with_items:
    - "{{ cluster_name }}-{{ regions.split(',')[0] }}"
    - "{{ cluster_name }}-{{ regions.split(',')[1] }}"

- name: Clean up working files
  file:
    path: "flux-helm-operator-deployment.yaml"
    state: absent
